In [9]:
#1. Import the NUMPY package under the name np...
import numpy as np

In [10]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)

1.19.2


In [11]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2,3,5).round(2)

In [12]:
#4. Print a.
print(a)

[[[0.7  0.99 0.47 0.29 0.82]
  [0.98 0.24 0.27 0.55 0.41]
  [0.47 0.37 0.24 0.96 0.32]]

 [[0.33 0.4  0.22 0.37 0.11]
  [1.   0.42 0.18 0.78 0.4 ]
  [0.7  0.08 0.24 0.69 0.41]]]


In [13]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

In [14]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

#In python we use len()

30
30


In [16]:
#8. Are you able to add a and b? Why or why not?
np.concatenate((a,b))
#all the input array dimensions for the concatenation axis must match exactly

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)


In [18]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a+c
# It has the same dimension

In [19]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[0.7  0.99 0.47 0.29 0.82]
  [0.98 0.24 0.27 0.55 0.41]
  [0.47 0.37 0.24 0.96 0.32]]

 [[0.33 0.4  0.22 0.37 0.11]
  [1.   0.42 0.18 0.78 0.4 ]
  [0.7  0.08 0.24 0.69 0.41]]]
[[[1.7  1.99 1.47 1.29 1.82]
  [1.98 1.24 1.27 1.55 1.41]
  [1.47 1.37 1.24 1.96 1.32]]

 [[1.33 1.4  1.22 1.37 1.11]
  [2.   1.42 1.18 1.78 1.4 ]
  [1.7  1.08 1.24 1.69 1.41]]]


In [20]:
#12. Multiply a and c. Assign the result to e.
e = a*c
e

array([[[0.7 , 0.99, 0.47, 0.29, 0.82],
        [0.98, 0.24, 0.27, 0.55, 0.41],
        [0.47, 0.37, 0.24, 0.96, 0.32]],

       [[0.33, 0.4 , 0.22, 0.37, 0.11],
        [1.  , 0.42, 0.18, 0.78, 0.4 ],
        [0.7 , 0.08, 0.24, 0.69, 0.41]]])

In [21]:
#13. Does e equal to a? Why or why not?
print(a.size)
print(e.size)
#Yes it does. Variable "c" is one, so "e" will be the same variable as "a"

30
30


In [22]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [23]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

In [24]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

SyntaxError: invalid syntax (<ipython-input-24-2656b6303ced>, line 2)

In [25]:
#funcion putmask
'''
condicion1 = d[(d>d_min)]
condicion2 = d[(d<d_mean)]
f = np.putmask(d,(condicion1 and condicion2).any(),25)
print(f)'''

'\ncondicion1 = d[(d>d_min)]\ncondicion2 = d[(d<d_mean)]\nf = np.putmask(d,(condicion1 and condicion2).any(),25)\nprint(f)'

In [26]:
lista_vacia = []
for i in d:
    for s in i:
        for n in s:
            if n > d_min and n < d_mean:
                lista_vacia.append(25)
            elif n > d_mean and n < d_max:
                lista_vacia.append(75)
            elif n == d_mean:
                lista_vacia.append(50)
            elif n == d_min:
                lista_vacia.append(0)
            elif n == d_max:
                lista_vacia.append(100)
                
            
            

In [27]:
print(lista_vacia)

[75, 75, 25, 25, 75, 75, 25, 25, 75, 25, 25, 25, 25, 75, 25, 25, 25, 25, 25, 25, 100, 25, 25, 75, 25, 75, 0, 25, 75, 25]


In [28]:
F= np.array(lista_vacia)
F

array([ 75,  75,  25,  25,  75,  75,  25,  25,  75,  25,  25,  25,  25,
        75,  25,  25,  25,  25,  25,  25, 100,  25,  25,  75,  25,  75,
         0,  25,  75,  25])

In [34]:
#17. Print d and f. Do you have your expected f?
print(d)
print(" ")
print(" ")
print(" ")
print(F)


[[[1.7  1.99 1.47 1.29 1.82]
  [1.98 1.24 1.27 1.55 1.41]
  [1.47 1.37 1.24 1.96 1.32]]

 [[1.33 1.4  1.22 1.37 1.11]
  [2.   1.42 1.18 1.78 1.4 ]
  [1.7  1.08 1.24 1.69 1.41]]]
 
 
 
[]


In [33]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
lista_letras = []
for i in F:
    if i == 0:
        lista_letras.append("A")
    elif i == 25:
        lista_letras.append("B")
    elif i == 50:
        lista_letras.append("C")
    elif i == 75:
        lista_letras.append("D")
    elif i == 100:
        lista_letras.append("E")
        
print(lista_letras)
#F = np.array(lista_letras)
#print(F.reshape(2,3,5))


[]
