In [38]:
import numpy as np

In [39]:
print(np.__version__)
print(np.show_config())

1.12.1
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files//Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files//Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files//Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files//Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files//Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files//Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_d

In [40]:
a = np.random.rand(2,3,5)
print(a)

[[[ 0.76971428  0.18846057  0.17913169  0.55296799  0.63693422]
  [ 0.85168889  0.61885798  0.34652133  0.58564207  0.19254133]
  [ 0.75277513  0.5613835   0.13534068  0.91480936  0.02369619]]

 [[ 0.81039595  0.77432236  0.05772652  0.41103632  0.15310943]
  [ 0.88893077  0.06099342  0.3948195   0.6795415   0.08122888]
  [ 0.070118    0.38780014  0.28816735  0.68635251  0.63776361]]]


In [41]:
b = np.ones((5,2,3))
print(b)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [42]:
a.size

30

In [43]:
b.size

30

In [44]:
if a.size == b.size:
    print(True)
else:
    print(False)

True


In [45]:
a_and_b = np.add(a, b)
print(a_and_b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [46]:
c = np.transpose(b, (1,2,0))

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [97]:
d = np.add(a, c)
print(d)

[[[ 1.76971428  1.18846057  1.17913169  1.55296799  1.63693422]
  [ 1.85168889  1.61885798  1.34652133  1.58564207  1.19254133]
  [ 1.75277513  1.5613835   1.13534068  1.91480936  1.02369619]]

 [[ 1.81039595  1.77432236  1.05772652  1.41103632  1.15310943]
  [ 1.88893077  1.06099342  1.3948195   1.6795415   1.08122888]
  [ 1.070118    1.38780014  1.28816735  1.68635251  1.63776361]]]


In [49]:
e = np.multiply(a, c)
print(e)

[[[ 0.76971428  0.18846057  0.17913169  0.55296799  0.63693422]
  [ 0.85168889  0.61885798  0.34652133  0.58564207  0.19254133]
  [ 0.75277513  0.5613835   0.13534068  0.91480936  0.02369619]]

 [[ 0.81039595  0.77432236  0.05772652  0.41103632  0.15310943]
  [ 0.88893077  0.06099342  0.3948195   0.6795415   0.08122888]
  [ 0.070118    0.38780014  0.28816735  0.68635251  0.63776361]]]


In [50]:
(e == a).all()

True

In [98]:
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)


1.9148093574
1.02369619321
1.45642571624


In [104]:
f = np.empty((2,3,5))
print(f)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [109]:
d = np.add(a, c)
print(d.shape)
print(len(d))

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
         
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
             
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
         
            if d[i][j][k] == d_mean:
                f[i][j][k] = 50
       
            if d[i][j][k] == d_min:
                f[i][j][k] = 0
          
            if d[i][j][k] == d_max:
                f[i][j][k] = 100                


print(d)    
print(f) 
    

(2, 3, 5)
2
[[[ 1.76971428  1.18846057  1.17913169  1.55296799  1.63693422]
  [ 1.85168889  1.61885798  1.34652133  1.58564207  1.19254133]
  [ 1.75277513  1.5613835   1.13534068  1.91480936  1.02369619]]

 [[ 1.81039595  1.77432236  1.05772652  1.41103632  1.15310943]
  [ 1.88893077  1.06099342  1.3948195   1.6795415   1.08122888]
  [ 1.070118    1.38780014  1.28816735  1.68635251  1.63776361]]]
[[[  75.   25.   25.   75.   75.]
  [  75.   75.   25.   75.   25.]
  [  75.   75.   25.  100.    0.]]

 [[  75.   75.   25.   25.   25.]
  [  75.   25.   25.   75.   25.]
  [  25.   25.   25.   75.   75.]]]
