In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
print(np.version.version)

1.19.5


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. 
# Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays.
# How many ways can you find?

In [4]:
a = np.random.randint(0,10,size=(2,3,5))

In [5]:
a2 = np.random.random((2,3,5))

In [6]:
a3 = np.random.rand(2,3,5)

In [7]:
a4 = np.random.sample((2,3,5))

In [8]:
#4. Print a.

In [9]:
print(a)

[[[3 8 0 3 8]
  [1 7 1 4 7]
  [9 5 0 6 2]]

 [[6 6 4 4 6]
  [1 1 4 7 7]
  [5 6 6 8 8]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [11]:
b = np.ones((5,2,3))

In [12]:
#6. Print b.

In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [15]:
print(a.shape == b.shape)

False


In [16]:
#8. Are you able to add a and b? Why or why not?

**$a + b$ can't be added, they are of different shape, not possible**

In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [18]:
c = b.reshape(2,3,5)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

test2 = np.random.randint(10,256,size=(2,3,5))
test2.shape

test3 = np.random.randint(10,256,size=(10,10))
test3.shape

dfa = np.random.randint(0,10,size=(2,3))

dfapd = pd.DataFrame(dfa)
print(dfapd)

In [19]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

**also valid numpy methods: np.add(a+c)**

In [20]:
d = a + c

In [21]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

***for every value in a, it has added the corresponding value of array b***

In [22]:
print(a)
print(d)


[[[3 8 0 3 8]
  [1 7 1 4 7]
  [9 5 0 6 2]]

 [[6 6 4 4 6]
  [1 1 4 7 7]
  [5 6 6 8 8]]]
[[[ 4.  9.  1.  4.  9.]
  [ 2.  8.  2.  5.  8.]
  [10.  6.  1.  7.  3.]]

 [[ 7.  7.  5.  5.  7.]
  [ 2.  2.  5.  8.  8.]
  [ 6.  7.  7.  9.  9.]]]


In [23]:
#12. Multiply a and c. Assign the result to e.

In [24]:
e = a * c
print(e)

[[[3. 8. 0. 3. 8.]
  [1. 7. 1. 4. 7.]
  [9. 5. 0. 6. 2.]]

 [[6. 6. 4. 4. 6.]
  [1. 1. 4. 7. 7.]
  [5. 6. 6. 8. 8.]]]


In [25]:
#13. Does e equal to a? Why or why not?

In [26]:
print(a)
print(e)

[[[3 8 0 3 8]
  [1 7 1 4 7]
  [9 5 0 6 2]]

 [[6 6 4 4 6]
  [1 1 4 7 7]
  [5 6 6 8 8]]]
[[[3. 8. 0. 3. 8.]
  [1. 7. 1. 4. 7.]
  [9. 5. 0. 6. 2.]]

 [[6. 6. 4. 4. 6.]
  [1. 1. 4. 7. 7.]
  [5. 6. 6. 8. 8.]]]


In [27]:
e == a
# python understands the float of an integer as the integer value when it is a whole number ending in .0

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [28]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [29]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [ ]:
#15. Now we want to label the values in d. 
# First create an empty array "f" 
# with the same shape (i.e. 2x3x5) as d 
# using `np.empty`.

In [31]:
f = np.empty((2,3,5))

In [32]:
print(f)

[[[3. 8. 0. 3. 8.]
  [1. 7. 1. 4. 7.]
  [9. 5. 0. 6. 2.]]

 [[6. 6. 4. 4. 6.]
  [1. 1. 4. 7. 7.]
  [5. 6. 6. 8. 8.]]]


In [42]:

"""
#16. Populate the values in f. 

For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. \n\nFor each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\n\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\n\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\n\nAssign 0 to the corresponding value(s) in f for d_min in d.\n\nAssign 100 to the corresponding value(s) in f for d_max in d.\n\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\n\nNote: you don't have to use Numpy in this question.\n"

In [43]:
f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[d_mean == d] = 50
f[d_min == d] = 0
f[d_max == d] = 100


"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [36]:
print(d)

[[[ 4.  9.  1.  4.  9.]
  [ 2.  8.  2.  5.  8.]
  [10.  6.  1.  7.  3.]]

 [[ 7.  7.  5.  5.  7.]
  [ 2.  2.  5.  8.  8.]
  [ 6.  7.  7.  9.  9.]]]


In [37]:
print(f)

[[[ 25.  75.   0.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [100.  75.   0.  75.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  75.  75.  75.]]]



"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [39]:
f2 = np.empty((2,3,5),dtype = object)

In [40]:
f2[(d_min < d) & (d < d_mean)] = "B"
f2[(d_mean < d) & (d < d_max)] = "D"
f2[d_mean == d] = "C"
f2[d_min == d] = "A"
f2[d_max == d] = "E"

In [41]:
print(f2)

[[['B' 'D' 'A' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['E' 'D' 'A' 'D' 'B']]

 [['D' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']]]
